[package]
name = "cancrizans"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.13.5"
anyhow = "1.0.58"

[dependencies.sdl2]
version = "0.35.2"
default-features = false
features = ["unsafe_textures"]